# 日志配置
logging:
  logPath: /tmp
  filename: kube-sidecar.log
  writeLog: false
  maxSize: 10
  maxBackups: 40
  maxAge: 10
# 便车容器相关
sidecar:
  name: sidecar
  image: fluent/fluent-bit:2.1.0
  imagePullPolicy: IfNotPresent
  requestsCPU: 250m
  requestsMemory: 512Mi
  limitsCPU: 250m
  limitsMemory: 512Mi
  readOnly: true
# 配置fluentBit
fluentBit:
  # fluentBit日志level,默认info"
  serviceLogLevel: info
  # 采集日志缓存大小
  inputMemBufLimit: 20MB
  # 采集日志刷新间隔
  inputRefreshInterval: 20
# namespace白名单
namespacesWhiteList:
  - kube-system
  - kube-public
  - default
  - kube-node-lease
  - weave
  - kubesphere-logging-system
  - fc-monitoring-system
  - istio-system
  - kubesphere-system
  - kubesphere-controls-system
  - kubesphere-monitoring-system
  - kubesphere-devops-system
  - kubesphere-monitoring-federated
# deployment白名单
deploymentWhiteList:
  - coredns
  - metrics-server
